Docker
plugmxlly/BackEndTasks pull request #1
Opened 2023-10-15 15:20 UTC by plugmxlly

2023-10-15 16:15 UTC, RetmixX requested changes
Молодец, что сразу сделал разделение на версии, с минусами, ну хоть так. Папку с исходным кодом не надо пихать в разные версии, лучше вынести ее и потом ссылаться на путь в разных версиях окружения. Для бэкенда нету настройки

2023-10-15 16:15 UTC, RetmixX commented on dev/.env
В гитхабе должен быть только .env.example, без заполненных переменных. .env должен находится в .gitignore

2023-10-15 16:15 UTC, RetmixX commented on dev/docker-compose.yml
> +      - 80:80
Порты в .env

2023-10-15 16:15 UTC, RetmixX commented on dev/docker-compose.yml
> +      - 5432:5432
Порт так же в енв

2023-10-15 16:15 UTC, RetmixX commented on dev/docker-compose.yml
> +      - 8080:8080
Так же в енв

2023-10-15 16:15 UTC, RetmixX commented on dev/docker-compose.yml
> +    image: adminer
Нету версии, вдруг скачается новая версия и что-то отвалится? Лучше сразу задать фиксированную версию

2023-10-15 16:15 UTC, RetmixX commented on dev/nginx/conf.d/nginx.conf
Нету настройки для пхп

2023-10-15 16:15 UTC, RetmixX commented on dev/public/asd.html
Не нужный файл

2023-10-15 16:15 UTC, RetmixX commented on dev/public/index.html
Так же не нужный файл

2023-10-15 16:15 UTC, RetmixX commented on prod/.env
Тоже самое, что и для дев

2023-10-15 16:15 UTC, RetmixX commented on prod/docker-compose.yml
> +      - /www:/var/www
В проде не лучшая идея прокидывать волюмы до файлов, лучше во время сборки их скопировать в контейнер

2023-10-15 16:15 UTC, RetmixX commented on prod/docker-compose.yml
> +      - ./public/:/var/www/public
Тоже самое

2023-10-15 16:15 UTC, RetmixX commented on prod/docker-compose.yml
> +      - 80:80
Порты

2023-10-15 16:15 UTC, RetmixX commented on prod/docker-compose.yml
> +  adminer:
В проде он вообще не нужен

2023-10-15 16:15 UTC, RetmixX commented on prod/nginx/conf.d/nginx.conf
Нету для пхп настройки

2023-10-15 16:15 UTC, RetmixX commented on prod/public/asd.html
Тоже самое

2023-10-15 16:15 UTC, RetmixX commented on prod/public/index.html
Так же не нужный файл

2023-10-15 16:27 UTC, jurapro requested changes
Андрей все по делу написал. Плюс README.md заполни нормально (опиши что и для чего у тебя, какие есть переменные и за что отвечают и пр.)

2023-10-16 02:29 UTC, RetmixX requested changes
У тебя должно быть минимум 3 папки, project, dev, prod

2023-10-16 02:29 UTC, RetmixX commented on dev/.env
Из репозитория на гите дельни этот файл

2023-10-16 02:29 UTC, RetmixX commented on prod/.env
Тоже самое

2023-10-16 02:29 UTC, RetmixX commented on prod/images/php/Dockerfile
> +ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini
![image](https://github.com/plugmxlly/BackEndTasks/assets/98283896/5d4a5bdf-fe11-48bc-abe7-7ae2cade9c45)
Фикси

2023-10-16 02:29 UTC, RetmixX commented on prod/public/index.html
Не нужный файл

2023-10-16 02:29 UTC, RetmixX commented on prod/nginx/conf.d/nginx.conf
Нету настройки для php

2023-10-16 02:29 UTC, RetmixX commented on prod/docker-compose.yml
> +      - 5432:5432
В .env

2023-10-16 02:29 UTC, RetmixX commented on dev/public/index.html
Убрать

2023-10-16 02:29 UTC, RetmixX commented on dev/nginx/conf.d/nginx.conf
Нету настройки для пхп

2023-10-16 12:46 UTC, RetmixX requested changes

2023-10-16 12:46 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
Волюмы в проде убирай

2023-10-16 12:46 UTC, RetmixX commented on prod/docker-compose.yml
> +  postgres:
Тут лучше добавь волюм, где будут хранится данные от бд. Вдруг контейнер навернется и тогда данные тоже умрут

2023-10-16 12:46 UTC, RetmixX commented on dev/.env
Убери .env с гитхаба

2023-10-16 12:46 UTC, RetmixX commented on dev/nginx/conf.d/nginx.conf
В конфиг для дева добавь маршрут до админера

2023-10-16 12:46 UTC, RetmixX commented on prod/.env
Так же дельник с гитхаба

2023-10-16 13:03 UTC, jurapro requested changes
Исправляй замечания от Андрея и на повтор

2023-10-16 13:13 UTC, plugmxlly commented on prod/docker-compose.yml
> +    volumes:
везде или только в nginxe?

2023-10-16 13:19 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
Везде, кроме бд

2023-10-17 01:31 UTC, jurapro approved these changes

2023-10-17 01:32 UTC, jurapro commented
Исправляй конфликт и сливайся

2023-10-17 06:32 UTC, merged